name: Cypress Tests

on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches: 
      - main
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: 
      image: cypress/included:13.16.0
      options: --ipc=host
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm ci
        
      - name: Start application
        run: npm start & npx wait-on http://localhost:3000
        
      - name: Run Cypress tests at electron
        run: npm run e2e:electron

      - name: Run Cypress tests at chrome
        run: npm run e2e:chrome

      - name: Run Cypress tests at chromium
        run: npm run e2e:chromium
          
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
